### ISSUE TITLE
不错的库，用 javapoet 生成代码感觉更好

### ISSUE THREAD

**Issue by a-voyager** [zhihu/SugarAdapter#3]
对 Java 代码直接硬编写维护性是否欠佳？

**Comment by mthli** [comment]
javapoet 生成的代码可读性不行，需要自己手动格式化；而且用各种 Spec 来拼代码其实也不怎么直观。之前是自己先手写好模版，然后做对应的字符串替换的，其实也没那么麻烦，有所取舍吧。
