### ISSUE TITLE
[feature request]: support for other bind data method from original RecyclerView.ViewHolder

### ISSUE THREAD

**Issue by Anthonyeef** [zhihu/SugarAdapter#4]
**problem description**
- SugarAdapter make a custom wrapper for RecyclerView.ViewHolder and only expose `onBindData()` method, which make it impossible to call other bind data method from the original RecyclerView.ViewHolder, such as: 

```
public void onBindViewHolder(VH holder, int position, List<Object> payloads) {
            onBindViewHolder(holder, position);
}
```

plz consider to add this method to `SugarViewHolder` as well.

**Comment by mthli** [comment]
https://github.com/zhihu/SugarAdapter/commit/317eb64121a0d88f907ecbb03f4b657380d3b43e
